# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b6de476ea0ae20f5a61f922168b41703c38d19f6b6fe289cd9047837c0631d1eeb789413bf695e9acc9005194f6c5c229b188aa1f333c70221e305769ec5ecf

test:
  secret_key_base: 5b2875fae976810ae5ef0b35acf2fea856054b05816609a511d9566779786684ac3180f322c58ac547749c7c5a054331285d21b7027aaaeab731904790e93fd2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
